### ISSUE TITLE
win版本读取路径后不出现小说内容

### ISSUE THREAD

**Issue by byjjack** [cteams/Thief-Book#10]
测试小说格式有
TXT、azw3、mobi、equb,以上格式均不能展示内容

**Comment by lauixData** [comment]
目前仅支持 TXT 格式，设置路径保存后，按 翻页快捷键试试？如果不行有可能是 快捷键冲突问题

**Comment by byjjack** [comment]
谢谢已经解决，就是快捷键冲突问题
