### ISSUE TITLE
置顶和一些其他小虫子

### ISSUE THREAD

**Issue by kannad** [cteams/Thief-Book#11]
- Windows ver. ：1803 (17134.860)家庭版
- Program ver. ：1.0.1
---
问题：

1. 置顶无效
2. 双击该窗口会导致全屏化，是否考虑设置鼠标穿越？
---
以上，感谢作者的开发！

**Comment by lauixData** [comment]
感谢使用！

1.请问是什么版本的系统 win7 or win10 什么
2.全屏化这是系统自带的功能，mac win linux 都有的，而且摸鱼是支持窗口随意拖动的，所以这个问题不予解决。另外 鼠标穿越是什么？ 穿透？

**Comment by kannad** [comment]
> 感谢使用！
> 
> 1.请问是什么版本的系统 win7 or win10 什么
> 2.全屏化这是系统自带的功能，mac win linux 都有的，双击就可以还原了，而且摸鱼是支持窗口随意拖动的，所以这个问题不予解决。另外 鼠标穿越是什么？ 穿透？

---
A：
1. Win10
2. 了解了&是的

**Comment by lauixData** [comment]
1.一会排查下
2.穿透这个需要调研下，如果没问题下次更新就加入

**Comment by kannad** [comment]
> 1.一会排查下
> 2.穿透这个需要调研下，如果没问题下次更新就加入

---
感激不尽！开发辛苦了，最后一个问题，如果没什么补充的话就可以close issue了

老板键的时候还是自动翻页，可以使其自动暂停/继续吗？

**Comment by lauixData** [comment]
老板键这个问题，是我考虑不周，下期更新会修改。
