### ISSUE TITLE
免安装版1.0.1，打开报错

### ISSUE THREAD

**Issue by smallwhale** [cteams/Thief-Book#13]
![image](https://user-images.githubusercontent.com/19883178/61101403-2d195880-a49c-11e9-9c23-c100cdf5e4c0.png)

**Comment by lauixData** [comment]
@smallwhale 看问题汇总里有说明，新版本会解决这个问题

**Comment by smallwhale** [comment]
> @smallwhale 看问题汇总里有说明，新版本会解决这个问题

可以了，设置txt路径后还是显示开机时长是什么原因？

**Comment by lauixData** [comment]
默认显示开机时间，按快捷键or点击下一页即可。

**Comment by smallwhale** [comment]
> 默认显示开机时间，按快捷键or点击下一页即可。

嗯嗯，好的，非常感谢
