### ISSUE TITLE
绿色便携版设置快捷键后报错

### ISSUE THREAD

**Issue by lonelydie** [cteams/Thief-Book#15]
![screenshot_20190716_152906](https://user-images.githubusercontent.com/36894410/61274495-83f59980-a7de-11e9-81b7-dd3687fe6252.png)
删除后重新解压也没用，

**Comment by lauixData** [comment]
看 文档，问题汇总有说明。下期会修复这个问题

**Comment by lonelydie** [comment]
好的,麻烦了
