### ISSUE TITLE
无法跳页

### ISSUE THREAD

**Issue by hu1240050829** [cteams/Thief-Book#3]
无法跳转到任意页，而且一页一页的翻感觉反应有些迟钝

**Comment by lauixData** [comment]
设置里 选择 Thief Book 修改当前页即可
迟钝问题，请问你的小说多少M？

**Comment by hu1240050829** [comment]
《希灵帝国》，改成UTF-8编码之后23M

**Comment by lauixData** [comment]
我这是Mac Pro 使用了个 50M 的小说 进行测试，并没有卡顿问题。有可能和 电脑配置有关。后期会优化IO性能
